-- MySQL Script generated by MySQL Workbench
-- Thu Nov  5 11:55:40 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema session_service
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `session_service` ;

-- -----------------------------------------------------
-- Schema session_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `session_service` DEFAULT CHARACTER SET utf8 ;
USE `session_service` ;

-- -----------------------------------------------------
-- Table `session_service`.`assigning_application`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session_service`.`assigning_application` ;

CREATE TABLE IF NOT EXISTS `session_service`.`assigning_application` (
  `application_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `description` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`application_id`),
  UNIQUE INDEX `application_name` (`name` ASC, `version` ASC) VISIBLE,
  UNIQUE INDEX `application_id_UNIQUE` (`application_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `session_service`.`production_database`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session_service`.`production_database` ;

CREATE TABLE IF NOT EXISTS `session_service`.`production_database` (
  `production_database_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`production_database_id`),
  UNIQUE INDEX `production_database_id_UNIQUE` (`production_database_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `session_service`.`session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session_service`.`session` ;

CREATE TABLE IF NOT EXISTS `session_service`.`session` (
  `session_id` INT NOT NULL AUTO_INCREMENT,
  `ses_application_id` INT NOT NULL,
  `ses_production_database_id` INT NOT NULL,
  `osid_idsetid` INT NULL COMMENT 'The OSID web-service id range starts at 1. But old stable_ids will not have an osid_idsetid',
  `data_check` ENUM('pass', 'fail', 'pending') NOT NULL DEFAULT 'pending',
  `message` TEXT(1000) NOT NULL,
  `creation_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`session_id`),
  INDEX `application_id_idx` (`ses_application_id` ASC) VISIBLE,
  INDEX `production_database_idx` (`ses_production_database_id` ASC) VISIBLE,
  UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC) VISIBLE,
  UNIQUE INDEX `osid_idsetid_UNIQUE` (`osid_idsetid` ASC) VISIBLE,
  CONSTRAINT `session_application_id`
    FOREIGN KEY (`ses_application_id`)
    REFERENCES `session_service`.`assigning_application` (`application_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `production_database`
    FOREIGN KEY (`ses_production_database_id`)
    REFERENCES `session_service`.`production_database` (`production_database_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `session_service`.`session_identifier_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session_service`.`session_identifier_action` ;

CREATE TABLE IF NOT EXISTS `session_service`.`session_identifier_action` (
  `session_identifier_action_id` INT NOT NULL AUTO_INCREMENT,
  `sia_stable_identifier_record_id` INT NOT NULL,
  `sia_session_id` INT NOT NULL,
  `action` ENUM('create', 'delete') NOT NULL,
  INDEX `sia_stable_identifier_record_id_idx` (`sia_stable_identifier_record_id` ASC) VISIBLE,
  INDEX `sia_session_id_idx` (`sia_session_id` ASC) VISIBLE,
  UNIQUE INDEX `session_identifier_action` (`sia_stable_identifier_record_id` ASC, `sia_session_id` ASC) VISIBLE,
  PRIMARY KEY (`session_identifier_action_id`),
  UNIQUE INDEX `session_identifier_action_id_UNIQUE` (`session_identifier_action_id` ASC) VISIBLE,
  CONSTRAINT `sia_stable_identifier_record_id`
    FOREIGN KEY (`sia_stable_identifier_record_id`)
    REFERENCES `session_service`.`stable_identifier_record` (`stable_identifier_record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sia_session_id`
    FOREIGN KEY (`sia_session_id`)
    REFERENCES `session_service`.`session` (`session_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `session_service`.`stable_identifier_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `session_service`.`stable_identifier_record` ;

CREATE TABLE IF NOT EXISTS `session_service`.`stable_identifier_record` (
  `stable_identifier_record_id` INT NOT NULL AUTO_INCREMENT,
  `stable_identifier` VARCHAR(100) NOT NULL,
  `status` ENUM('current', 'obsolete') NOT NULL DEFAULT 'current',
  `feature_type` ENUM('gene', 'transcript', 'translation') NOT NULL,
  PRIMARY KEY (`stable_identifier_record_id`),
  UNIQUE INDEX `name_status` (`stable_identifier` ASC, `status` ASC) VISIBLE,
  UNIQUE INDEX `stable_identifier_record_id_UNIQUE` (`stable_identifier_record_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
